/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmortizationTable: typeof import('./../components/data/AmortizationTable.vue')['default']
    AppBadge: typeof import('./../components/ui/AppBadge.vue')['default']
    AppButton: typeof import('./../components/ui/AppButton.vue')['default']
    AppCard: typeof import('./../components/ui/AppCard.vue')['default']
    AppInput: typeof import('./../components/ui/AppInput.vue')['default']
    AppModal: typeof import('./../components/ui/AppModal.vue')['default']
    AppPagination: typeof import('./../components/ui/AppPagination.vue')['default']
    AppSelect: typeof import('./../components/ui/AppSelect.vue')['default']
    AppSkeleton: typeof import('./../components/ui/AppSkeleton.vue')['default']
    AppTable: typeof import('./../components/ui/AppTable.vue')['default']
    AppTabs: typeof import('./../components/ui/AppTabs.vue')['default']
    AppToast: typeof import('./../components/ui/AppToast.vue')['default']
    AppToggle: typeof import('./../components/ui/AppToggle.vue')['default']
    EmptyState: typeof import('./../components/feedback/EmptyState.vue')['default']
    ErrorState: typeof import('./../components/feedback/ErrorState.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IndexRatesWidget: typeof import('./../components/data/IndexRatesWidget.vue')['default']
    MetricCard: typeof import('./../components/data/MetricCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
